import type { ParsedPollData } from '../types';
import { parsePollData } from '../parser';
import { fetchWikipediaPolling, WikiFetchError, type WikiFailureKind, type WikiRequestOptions } from '../mediawikiApi';
import { backfillAffiliationFromCandidates } from '../partyColors';
import { GROUP_COUNTRY, type RaceDef } from './registry';

// Client-side race loading with a safety net. Order of preference:
//   1. a fresh copy in this browser (localStorage, 6 h)        -> source 'browser-cache'
//   2. a live Wikipedia fetch (MediaWiki Action API)            -> source 'live'
//   3. the bundled JSON in public/data/races/<id>.json          -> source 'fallback' (written by CI from real
//      Wikipedia data every day) or 'seed' (an illustrative placeholder shipped before the first CI run)
// A failed live request (timeout / offline / CORS / rate limit / no table) NEVER blanks the card: it drops to (3)
// and reports why, so the UI can show a Retry button.

export type RaceSource = 'live' | 'browser-cache' | 'fallback' | 'seed' | 'none';

export interface RaceLoad {
  raceId: string;
  source: RaceSource;
  parsed: ParsedPollData;
  fetchedAt: string;
  pageTitle?: string;
  sectionTitle?: string;
  /** why the live fetch was not used (set for fallback / seed / none) */
  error?: { kind: WikiFailureKind | 'unknown'; message: string };
  note?: string;
}

export interface FallbackFile {
  raceId: string;
  fetchedAt: string;
  pageTitle?: string;
  sectionTitle?: string;
  /** true for the illustrative placeholders generated by scripts/seed-race-fallbacks.mts */
  synthetic?: boolean;
  note?: string;
  parsed: Pick<ParsedPollData, 'parties' | 'rows'> & Partial<ParsedPollData>;
}

export interface LoaderDeps {
  fetchImpl?: typeof fetch;
  fetchJson?: (url: string) => Promise<unknown>;
  storage?: Pick<Storage, 'getItem' | 'setItem'> | null;
  now?: () => number;
  wiki?: WikiRequestOptions;
}

const TTL_MS = 6 * 3600_000;
const KEY = (id: string) => `probcalc.race.v2.${id}`;
const BASE: string = ((import.meta as unknown as { env?: { BASE_URL?: string } }).env?.BASE_URL) ?? '/';

function defaultStorage(): LoaderDeps['storage'] {
  try { return typeof localStorage !== 'undefined' ? localStorage : null; } catch { return null; }
}
const defaultFetchJson = async (url: string) => {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status}`);
  return r.json();
};

/** True when a parse yielded something BaseCalc can use: dated rows with sample sizes and values. */
export function hasUsablePolls(p: ParsedPollData): boolean {
  return p.parties.length > 0 && p.rows.some((r) => !r.isElectionResult && r.fieldworkEnd && r.sampleSize && Object.keys(r.values).length > 0);
}

/**
 * Backfills party affiliation/color for columns that only give a bare candidate surname
 * (no "Democratic"/"Republican" word in the header) against the real nominees a RaceDef
 * already knows, when it knows any — a no-op for races without demCandidate/repCandidate
 * (i.e. every non-US-midterm race, unaffected).
 */
function withKnownCandidates(parsed: ParsedPollData, def: RaceDef): ParsedPollData {
  if (!def.demCandidate && !def.repCandidate) return parsed;
  return { ...parsed, parties: backfillAffiliationFromCandidates(parsed.parties, def) };
}

// ---- concurrency: never more than 3 live Wikipedia requests in flight from the whole app ----------
let active = 0;
const waiting: (() => void)[] = [];
async function withSlot<T>(fn: () => Promise<T>): Promise<T> {
  if (active >= 3) await new Promise<void>((r) => waiting.push(r));
  active++;
  try { return await fn(); }
  finally { active--; waiting.shift()?.(); }
}
const inflight = new Map<string, Promise<RaceLoad>>();

export function loadRace(def: RaceDef, opts: { force?: boolean } & LoaderDeps = {}): Promise<RaceLoad> {
  const key = def.id + (opts.force ? ':force' : '');
  const running = inflight.get(key);
  if (running && !opts.fetchImpl) return running; // de-dupe identical requests from many cards (tests inject fetchImpl and skip this)
  const p = loadRaceUncached(def, opts).finally(() => inflight.delete(key));
  if (!opts.fetchImpl) inflight.set(key, p);
  return p;
}

async function loadRaceUncached(def: RaceDef, deps: { force?: boolean } & LoaderDeps): Promise<RaceLoad> {
  const storage = deps.storage === undefined ? defaultStorage() : deps.storage;
  const now = deps.now ?? Date.now;
  const fetchJson = deps.fetchJson ?? defaultFetchJson;

  if (!deps.force && storage) {
    try {
      const hit = JSON.parse(storage.getItem(KEY(def.id)) ?? 'null') as RaceLoad | null;
      if (hit && now() - Date.parse(hit.fetchedAt) < TTL_MS && hasUsablePolls(hit.parsed)) return { ...hit, source: 'browser-cache' };
    } catch { /* corrupt entry — ignore */ }
  }

  let failure: NonNullable<RaceLoad['error']>;
  try {
    const res = await withSlot(() =>
      fetchWikipediaPolling(def.wikiPage, def.wiki, def.sectionHint, { ...deps.wiki, fetchImpl: deps.fetchImpl, searchQuery: def.searchQuery })
    );
    const parsed = withKnownCandidates(parsePollData(res.wikitext, { country: GROUP_COUNTRY[def.group] }), def);
    if (!hasUsablePolls(parsed)) throw new WikiFetchError('no-table', `No usable polling table in "${res.sectionTitle}" of ${res.pageTitle}`);
    const load: RaceLoad = {
      raceId: def.id, source: 'live', parsed, fetchedAt: new Date(now()).toISOString(), pageTitle: res.pageTitle, sectionTitle: res.sectionTitle,
      note: res.resolvedFrom ? `Resolved "${res.resolvedFrom}" to "${res.pageTitle}"` : undefined,
    };
    try { storage?.setItem(KEY(def.id), JSON.stringify(load)); } catch { /* quota / private mode */ }
    return load;
  } catch (e) {
    failure = e instanceof WikiFetchError ? { kind: e.kind, message: e.message } : { kind: 'unknown', message: e instanceof Error ? e.message : String(e) };
  }

  try {
    const file = (await fetchJson(`${BASE}data/races/${def.id}.json`.replace(/\/{2,}/g, '/'))) as FallbackFile;
    const parsed: ParsedPollData = withKnownCandidates({ warnings: [], format: 'wikitext', ...file.parsed }, def);
    if (!hasUsablePolls(parsed)) throw new Error('fallback file holds no usable polls');
    return {
      raceId: def.id, source: file.synthetic ? 'seed' : 'fallback', parsed, fetchedAt: file.fetchedAt,
      pageTitle: file.pageTitle, sectionTitle: file.sectionTitle, error: failure, note: file.note,
    };
  } catch {
    return { raceId: def.id, source: 'none', parsed: { parties: [], rows: [], warnings: [], format: 'unknown' }, fetchedAt: new Date(now()).toISOString(), error: failure };
  }
}

export function describeFailure(e: RaceLoad['error']): string {
  if (!e) return '';
  switch (e.kind) {
    case 'timeout': return 'Wikipedia took too long to answer';
    case 'network': return 'Could not reach Wikipedia (offline or blocked)';
    case 'rate-limit': return 'Wikipedia is rate-limiting requests';
    case 'missing-page': return 'That Wikipedia page does not exist (yet)';
    case 'no-table': return 'No polling table on the page yet';
    default: return e.message;
  }
}
